# Week 1 of ML Zoomcamp - intro

### Import libraries

In [28]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

### Load the dataset

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-19 11:08:51--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1,4M) [text/plain]
Saving to: ‘housing.csv.1’

housing.csv.1       100%[===================>]   1,36M  5,75MB/s    in 0,2s    

2023-09-19 11:08:52 (5,75 MB/s) - ‘housing.csv.1’ saved [1423529/1423529]



### Basic EDA

In [31]:
housing_df = pd.read_csv('housing.csv')

In [32]:
housing_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [90]:
len(housing_df)

20640

### Question 1. What is the pandas version that you installed?

In [33]:
pd.__version__

'1.5.2'

### Question 2. How many columns are in the dataset?

In [34]:
len(housing_df.columns)

10

### Question 3. Which columns in the dataset have missing values?

In [35]:
housing_df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

### Question 4. How many unique values does the ocean proximity have?

In [36]:
housing_df['ocean_proximity'].nunique()

5

### Question 5. What's the average value of the median_house_value for the houses located near the bay?

In [37]:
near_bay_houses = housing_df[housing_df['ocean_proximity'] == 'NEAR BAY']

In [38]:
near_bay_houses['ocean_proximity'].unique()

array(['NEAR BAY'], dtype=object)

In [39]:
near_bay_houses

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
19067    -122.45     38.28                20.0       3306.0           503.0   
19068    -122.47     38.29                14.0       3732.0           846.0   
19069    -122.45     38.27                25.0       5024.0           881.0   
19077    -122.49     38.27                 8.0       5092.0           988.0   
19104    -122.51     38.17                 8.0       5875.0          1115.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
19067      1374.0       460.0         5.7984            297600.0   
19068      1277.0       775.0         2.5658            208000.0   
19069      1994.0       838.0         4.2237            262300.0   
19077      1657.0       936.0         3.5625            213200.0   
19104      2808.0      1029.0         3.6392            246300.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
19067        NEAR BAY  
19068        NEAR BAY  
19069        NEAR BAY  
19077        NEAR BAY  
19104        NEAR BAY  

[2290 rows x 10 columns]

In [41]:
near_bay_houses['median_house_value'].mean()   # the answer to the question 5

259212.31179039303

### Question 6

In [42]:
# Calculate the average of total_bedrooms column in the dataset.
mean_bedrooms = housing_df['total_bedrooms'].mean()

In [43]:
mean_bedrooms

537.8705525375618

In [44]:
# Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
housing_df['total_bedrooms'].fillna(mean_bedrooms, inplace=True)

In [45]:
housing_df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms        False
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

In [46]:
# Now, calculate the average of total_bedrooms again.
housing_df['total_bedrooms'].mean()

537.8705525375617

In [47]:
# The average of total_bedrooms column hasn't changed

### Question 7

In [56]:
housing_df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [57]:
housing_df['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [58]:
# Select all the options located on islands.
island_houses = housing_df[housing_df['ocean_proximity'] == 'ISLAND']

In [59]:
island_houses

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [60]:
# Select only columns housing_median_age, total_rooms, total_bedrooms.
island_houses = island_houses[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [61]:
island_houses

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [73]:
# Get the underlying NumPy array. Let's call it X.
X = island_houses.to_numpy()

In [74]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [75]:
X.shape

(5, 3)

In [76]:
# Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.
XTX = np.dot(X.T, X)

In [77]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [84]:
# Compute the inverse of XTX.
XTX_inverse = np.linalg.inv(XTX)

In [79]:
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [85]:
# Create an array y with values [950, 1300, 800, 1000, 1300].
y = np.array([950, 1300, 800, 1000, 1300])

In [87]:
y

array([ 950, 1300,  800, 1000, 1300])

In [88]:
# Multiply the inverse of XTX with the transpose of X, 
# and then multiply the result by y. Call the result w.
w = np.dot(np.dot(XTX_inverse, X.T),y)

In [89]:
# What is the value of the last element of w?
w[-1]

5.699229455065586